In [2]:
import numpy as np

In [24]:
sa = np.array([[5,6,7,8,9,10,11,12,13,14]])
af = np.array([[5,6,7,8,9,10,11,12,13,14]], dtype=float)
array2 = af.reshape((2,5))
print(array2)
print(array2.shape)

[[ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]]
(2, 5)


In [35]:
np.take(array2, [[2, 3], [7, 8]])

array([[ 7.,  8.],
       [12., 13.]])

In [31]:
print(array2[:,2:4])

[[ 7.  8.]
 [12. 13.]]


In [36]:
array2[array2 > 6]

array([ 7.,  8.,  9., 10., 11., 12., 13., 14.])

In [4]:
StudentName = ['John', 'Mike', 'Sarah', 'Kate', 'Samuel']
Score = [78, 95, 84, 98, 88]
#name_score = np.append([StudentName],[Score], axis=0)
name = list(StudentName)
sc = list(Score)
dict1 = {item : name[index] for index, item in enumerate(sc)}
dict1

{78: 'John', 95: 'Mike', 84: 'Sarah', 98: 'Kate', 88: 'Samuel'}

In [5]:
new_dict = sorted(dict1)
new_dict
## ????

[78, 84, 88, 95, 98]

In [71]:
import pandas as pd
data = pd.read_csv('titanic_train.csv')

In [72]:
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [75]:
data.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [77]:
data['Age_0'] = 0
data.loc[data['Age']!=0,'Age_0'] = 1
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_0  
0      0         A/5 21171   7.2500   NaN        S      1  
1      0          PC 17599  71.2833   C85        C      1  
2      0  STON/O2. 3101282   7.9250   NaN        S      1  
3      0            113803  53.1000  C123        S      1  
4      0            373450   8.0500   NaN        S      1

In [81]:
data['Age_by10'] = (data['Age']//10)*10
data['Family'] = data['SibSp']+data['Parch']+1
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_0  Age_by10  Family  
0      0         A/5 21171   7.2500   NaN        S      1      20.0       2  
1      0          PC 17599  71.2833   C85        C      1      30.0       2  
2      0  STON/O2. 3101282   7.9250   NaN        S      1      20.0       1  
3      0            113803  53.1000  C123        S      1      30.0       2  
4      0            373450   8.0500   NaN        S      1      30.0       1

In [86]:
data.drop(columns=['SibSp','Parch']).head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  \
0                            Braund, Mr. Owen Harris    male  22.0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
2                             Heikkinen, Miss. Laina  female  26.0   

             Ticket     Fare Cabin Embarked  Age_0  Age_by10  Family  
0         A/5 21171   7.2500   NaN        S      1      20.0       2  
1          PC 17599  71.2833   C85        C      1      30.0       2  
2  STON/O2. 3101282   7.9250   NaN        S      1      20.0       1

In [90]:
data.groupby(['Age_by10','Sex']).count()["PassengerId"]

Age_by10  Sex   
0.0       female     30
          male       32
10.0      female     45
          male       57
20.0      female     72
          male      148
30.0      female     60
          male      107
40.0      female     32
          male       57
50.0      female     18
          male       30
60.0      female      4
          male       15
70.0      male        6
80.0      male        1
Name: PassengerId, dtype: int64